python main_finetune.py \
    --accum_iter 4 \
    --batch_size 256 \
    --model vit_base_patch16 \
    --output_dir './output_dir_finetune_imagenet_0_05_revision_1epoch' \
    --log_dir './output_dir_finetune_imagenet_0_05_revision_1epoch' \
    --cls_token \
    --finetune '/mnt/ceph/image_tasks_rwm/mae/output_dir_h200_loss_0_05_checkpoint/checkpoint-750.pth' \
    --epochs 100 \
    --blr 5e-4 --layer_decay 0.65 \
    --weight_decay 0.05 --drop_path 0.1 --mixup 0.8 --cutmix 1.0 --reprob 0.25 \
    --dist_eval --data_path '/mnt/ceph/image_tasks_rwm/dataset'
