python main_pretrain.py \
    --resume './output_dir_h200_loss_0_05_checkpoint/checkpoint-478.pth' \
    --output_dir './output_dir_h200_loss_0_05_checkpoint' \
    --log_dir './output_dir_h200_loss_0_05_log' \
    --batch_size 512 \
    --world_size 1 \
    --model mae_vit_base_patch16 \
    --norm_pix_loss \
    --mask_ratio 0.75 \
    --epochs 800 \
    --warmup_epochs 40 \
    --data_path '/mnt/ceph/image_tasks_rwm/dataset' \
    --blr 1.5e-4 \
    --weight_decay 0.05
